version: '2'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./manage_staff/:/manage/manage_staff/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
     - POSTGRES_DB=test
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1
    
    
volumes:
  postgres_data: