# Generated by Django 2.2 on 2024-04-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employees_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('avata', models.ImageField(default=None, upload_to='Image')),
                ('file_image', models.FileField(default=None, upload_to='folder')),
            ],
        ),
    ]
