# Generated by Django 5.0.6 on 2024-05-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_attendance_local_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location_check',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
