# Generated by Django 5.0.6 on 2024-05-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_attendance_location_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
