# Generated by Django 5.0.6 on 2024-05-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_atendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='atendance',
            new_name='attendance',
        ),
    ]
