# Generated by Django 5.0.6 on 2024-05-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_atendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
